# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='analysis_utils',
    version='0.1.0',
    python_requires='==3.*,>=3.6.0',
    author='John Shanahan',
    author_email='shanahan.jrs@gmail.com',
    packages=['analysis_utils'],
    package_dir={"": "."},
    package_data={},
    install_requires=['msgpack==0.*,>=0.6.1', 'pydantic==1.*,>=1.6.1', 'python-dateutil==2.*,>=2.8.1'],
)
